### ISSUE TITLE
multiple instance conflicts - select is removed from the DOM

### ISSUE THREAD

**Issue by badpenguin** [brianvoe/slim-select#144]
I've 3 instances of slimselect, i've created them via
```new Slimselect({selector:'#uniqueid'});```

I've the following problems:
1) the Jquery change event will only work on the first instance i've created - for the other 2 instances will not bubble. However attaching for testing an old onchange="test()" on the select wlil work;
2) retrieving value via $('#uniqueid').val() will only work on the first instance;
3) if i choose any option on any instance the width of all the other 2 instances will change;

**Comment by badpenguin** [comment]
The change event is not triggered because all the SELECT tag except the 1st one gets removed from the DOM.

**Comment by badpenguin** [comment]
The SELECT tags get removed when calling 
``instance2.setData(....)```
from the instance1 change event.

**Comment by brianvoe** [comment]
Im sorry but this is tough to follow your issue. Nothing Im hearing you talk about has ever been an issue when using slim select. I cant tell if your trying to use an id 3 times which in and of itself would/should be problematic due to the nature of id's that should only be used once. As far as removal from the dom slim select doesnt remove anything from the dom except itself and thats only if you call destroy.

**Comment by badpenguin** [comment]
All select have a different id

**Comment by brianvoe** [comment]
Ill reopen if you can provide a decent gif of what your experiencing, enough that shows an actual slim select problem and not just a user error. I am more than willing to help, but im blind to your situation and nothing your describing adds up.

**Comment by badpenguin** [comment]
ok, trying to setup a codepen
