### ISSUE TITLE
onBlur event not happening

### ISSUE THREAD

**Issue by IrvingArmenta** [brianvoe/slim-select#146]
I am using `Formik` (https://github.com/jaredpalmer/formik) for form validation and the `<select />` field needs to be `touched` in order to properly show error messages.

`touched` is setup on the `onBlur` event of the `<select />` , however, since the "real" `<select />` is setup with `display: none` , the `focus()` event never happens so the `blur()` event never happens either. 

I think the `focus()` on the `<div />` generated by `new Slim` should be `wired` to trigger the event in someway in the parent `hidden` `<select />`.

I can make it work if I remove the `display: none` and add a `sr-only` class to the parent `<select />`  to hide it just visually. I have this event on the `new Select` 

```
 beforeClose: () => { 
                const select = document.getElementById(`${this.props.id}`);  
                if (select) {
                    select.focus();
                }
            },
```
I am using `react` with `typescript`, the `new Slim` is created on `componentDidMount()`

Perhaps an `onBlur` method could be added to the `new Slim` just like the `onChange` at the moment.

**Comment by brianvoe** [comment]
I think this situation is a bit specific toward your individual needs. Given there are a handful methods you can use to "touch" the original select to facilitate your needs, I think it would be best if you used those methods instead of having slim perform a focus on the original select which would open a new set of problem(especially for mobile).

Because i have used slim select along side of validations I would suggest manually dealing with this validation on its own outside of the validation package your using.
