### ISSUE TITLE
Height on select change container height but not select

### ISSUE THREAD

**Issue by stanolacko** [brianvoe/slim-select#162]
If `<select>` had set height, slim select copy this style to container. But it not affect height of selector.
This example uses innerHTM with image height 40px.

On Single -select had fixed height by CSS (30px)

- image is cropped due to padding of ss-single-selected.

On Multiple - select dynamicaly changed to height of selected item

- image is fully displayed

[Example on JSFiddle](https://jsfiddle.net/2n0v5br3/)

1. If height is copied to container, it will be better to copy it to sindleSelectedDiv and multipleSelectedDiv.
2. Can single select also change height if innerHTML is used?

**Comment by stanolacko** [comment]
Anyway, added `container.style.cssText = this.main.config.style;` in `Slim.prototype.singleSelectedDiv` solve this issue when copy height of original `<select>`.
This is not solving dynamic height of innerHTML as in multiple

**Comment by brianvoe** [comment]
I need to better see what your experiencing. Can you attach a gif or something?

**Comment by stanolacko** [comment]
I prepare new JSFiddle which shows, that on single select, select had always fixed height but on multiple hieght of selector is dymamic. So expecting is to show full innerHTML in selector

[JSFiddle](https://jsfiddle.net/aj9v5ugh/)

![image](https://user-images.githubusercontent.com/1910456/62732346-66ee6800-ba24-11e9-80cd-9d26f413f3ab.png)

**Comment by brianvoe** [comment]
Im not sure i fully follow. Are you suggesting that you think if you change the height on the original select dynamically it would change the height on slim select? If so that is not how it works. It only pull any styles from the original select upon initiation of slimselect.

Im not sure why you would even want it to work that way. If you need a dynamic height add a wrapper div and change the height on that and just make your select height: 100%;

**Comment by stanolacko** [comment]
Sorry this is mis understanding.
1. I was showing current sittuation thet if original `<select>` have set style for example  `style="width:100px"` than wrapper ss-main copy this `<div class="ss-71551 ss-main" style="width: 100px;">`
This have no sense becaouse it you create empty gap between SlimSelect and other elements in form.
2. Main question is why single select not set height dynamicaly if multiple does.

I understand that for backward compatibility can be problem to set this automaticaly.
If there will be new config parameter called for example dynamicHeight = false, and when true, single select will change height by the height of select item, the same way how on multiple

**Comment by davegomez** [comment]
I'm experiencing the same issue and I'll try to explain it better.

When I apply styles to my `select` in order to modify its appearance, I would expect these styles to be inherited by Slim Select and make the select look like the original one.

The problem is that my select classes or inline styles are being copy to the element with the class name `ss-main` (the container) instead of the element with the class name `ss-single-selected` (the select).

The most basic example can be to apply the following CSS to my select:

```css
select {
    border: 1px solid red;
    padding: 8px;
}
```

And this would be the result:

<img width="652" alt="image" src="https://user-images.githubusercontent.com/282903/132262165-02c7ef83-e20b-45a5-9cf0-3a7ec991d89f.png">
