### ISSUE TITLE
Dynamic load options when scroll select

### ISSUE THREAD

**Issue by dejurin** [brianvoe/slim-select#23]

**Comment by brianvoe** [comment]
Can you be a little more specific please?

**Comment by dejurin** [comment]
When scrolling down the list are loading more options.

**Comment by brianvoe** [comment]
What is your current use case that is so large that you need progressive loading?

You could trigger a server request using the search callback and update the options list for matching results.

**Comment by yellow1912** [comment]
Lets say that you have a huge list of items, many with similar name, then your search result may return more than expected. It should be nice to show that there's more results that can be loaded.

**Comment by brianvoe** [comment]
So at this point you basically have two options. Either load all the data into your slim select no matter how large it is or alter your use case to be more specific about about exactly what your searching. As of right now slim select can have a good amount of values in the dropdown.

The tricky thing about this is if you have a incredibly large amount of options that all have similar names I would suggest you might have a more underlying issue regarding your data that you might want to address first.

Otherwise i would love to see what this data looks like that cant easily be ajax searched.
