### ISSUE TITLE
Uncaught Error: Could not find select element

### ISSUE THREAD

**Issue by reasecret** [brianvoe/slim-select#299]
I've installed slim-select on Laravel 8 but getting an error: "Uncaught Error: Could not find select element"

```
	<link href="{{ asset('css/slimselect.css') }}" rel="stylesheet">
	<script src="{{ asset('js/slimselect.js') }}"></script>
	
	<select id="multiple" multiple>
		<option value="value 1">Value 1</option>
		<option value="value 2">Value 2</option>
		<option value="value 3">Value 3</option>
	</select>
	
	<script>
		new SlimSelect({
            select: '#multiple'
        });
	</script>
```

![resim](https://user-images.githubusercontent.com/32717963/127397974-ac38f7aa-7d54-4bd6-9a5e-192917bee9fd.png)

What should I do?

**Comment by diderich** [comment]
I think you need to put the script section after/below the select statement.

**Comment by reasecret** [comment]
> 
> 
> I think you need to put the script section after/below the select statement.

I already wrote like that. The code above is just example.

```
@section('content')
    <select id="skillSelect" multiple>
        <option value="1">Option 1</option>
        <option value="2">Option 2</option>
        <option value="3">Option 3</option>
        <option value="4">Option  4</option>
    </select>
@endsection
@push('css')
	<link href="{{ asset('css/slimselect.css') }}" rel="stylesheet"></link>
@endpush
@push('scripts')
	<script src="{{ asset('js/slimselect.js') }}"></script>
	<script>
		new SlimSelect({
            select: '#skillSelect'
        });
	</script>
@endpush
```

**Comment by kashishahuja2002** [comment]
"<script>
		new SlimSelect({
            select: '#skillSelect'
        });
</script>"

This script is loading before the document is loaded and HTML is rendered, that's why it is not finding the select element.
Keep this script code inside "document.onload".

**Comment by brianvoe** [comment]
I dont think this is an actual issue. So im going to close it. New version 2 released today!

**Comment by blakepell** [comment]
Something to keep in mind also akin to the path @kashishahuja2002 went down, depending on what JavaScript frameworks you might be using it with the element has to exist at the time SlimSelect initialized.  I'm using it with Vue3 and I ran into an issue where I used a `v-if` and `v-else` when dynamically loading a form (in Vue, `v-if` determines not just if it's visble but if it's literally been rendered).  Because the `SlimSelect` was in my `v-else` it didn't exist at the time I tried to initialize it.

In my case it wasn't good enough to do it onload or Vue's `mounted()` but the select didn't exist yet.

If Laravel loading your form on the fly (via Ajax, constructing it, etc.) then you need to figure out how to init SlimSelect _after_ that runs.
