### ISSUE TITLE
timeoutDelay broken with v2.0.0

### ISSUE THREAD

**Issue by rbclark** [brianvoe/slim-select#359]
**Describe the bug**
With version `1.27.0` we were setting `timeoutDelay` to 0 in order to fix an issue when running slimSelect in tests where the test suite would click on an option before the animation was complete and we would end up in a state where the tests were unable to continue since the dropdown was still active even after click.

In 2.0.0 this no longer works for 2 reasons:

1. timeoutDelay cannot be set to 0 any longer due to [the code](https://github.com/brianvoe/slim-select/blob/61dd471ce0240c73681980823869570b099bde68/src/slim-select/settings.ts#L66) and `0 || 200 == 200`. The original intent of timeoutDelay as far as I can tell was so that users could set it to a very low value or 0 to avoid timing issues https://github.com/brianvoe/slim-select/issues/122.
2. When I do set the value to something very low like `1` the behavior is now very different. It now very quickly closes the dropdown on first expand. Subsequent expands work properly for some reason. The screengrab below reproduces the issue. In order to do this I am initializing with the following block:

```
    new SlimSelect({
      select: '#element',
      settings: {
        timeoutDelay: 1
      }
    });
```

All I really need is a way to let the test suite click through quickly while still closing the dropdown after click so if you have any other suggestions on how to achieve that I'd be happy to hear them.

**Screenshots**

https://user-images.githubusercontent.com/2308869/203093870-98dfe3c0-acf5-4885-b7c1-06353317505b.mov

**Comment by brianvoe** [comment]
I think I understand your issue. One of the messy things about javascript is timing. I have setTimeouts in various locations in slim select to allow the css animation to complete before setting something like isOpen: false after a certain period of time. I would like to try to address these animation issues with javascript instead of css so that way i can more programmably set timeouts that would better adhere to settings of specific animation durations.

Unfortunately I will have to put this on the list of todos for now. But i will create an issue specifically tackling the animation stuff i talked about. If you think you have a quick fix for now until I make the necessary updates then please submit a pr and ill try to get to it soon. Thanks.
