### ISSUE TITLE
Using allowDeselect setting

### ISSUE THREAD

**Issue by oleksiivelychko** [brianvoe/slim-select#430]
Hi. I've included SlimSelect library and that works great but I'm confused a little bit about default option.
So, my settings looks like:
```
settings: {
            allowDeselect: true
},
```
and when I click on x button my data is not being cleared from select at all.
<img width="298" alt="image" src="https://user-images.githubusercontent.com/94033630/213860015-d7dc81e7-1be2-42f5-9316-2794189d619d.png">

I see in documentation I have to add default as:
`<option data-placeholder="true"></option>`
... but how? So, my question - how I can add default option to clear all data into select? or, that might be added automatically through setting or event?

Thanks.

**Comment by brianvoe** [comment]
So in order to "deselect" something you need to have SlimSelect select an option that is an empty string. All SlimSelect is doing when you click the X is setting the value to "". I think the docs describe it well enough, if you have any suggestions for updates please let me know. https://slimselectjs.com/settings#allowDeselect

**Comment by jorbs** [comment]
@brianvoe there is an issue with `allowDesect` when you set the options through `data` setting. The x icon isn't displayed.

I understand that in order to make the icon appear, there must be an option with `value=""`. The problem is that when I prepend an empty value option to my options, the library sets its value to the placeholder text. For example:

```
new SlimSelect({
            select: document.getElementById('manufactures'),
            data: [{text: 'Manufacturer', value: "", placeholder: true}].concat(manufacturers),
            settings: {
              allowDeselect: true
            }
          });
```

The x icon isn't displayed and the first select option is rendered like:
```
<option value="Manufacturer" data-placeholder="true">Manufacturer</option>
```

I believe that the `text` option shouldn't be mandatory if the option is a placeholder.
