### ISSUE TITLE
[FEATURE REQUESTS] Unselect multiple select options one by one using backspace and clear all button

### ISSUE THREAD

**Issue by The-Magicians-Code** [brianvoe/slim-select#456]
I've chosen Slim-Select over Chosen-Select because of it's compact size, good documentation, mobile usability (Chosen-Select does not work on mobiles) and small amount of dependencies, but I'd still like to deselect multiple select options one by one by pressing backspace, also a clear all x or button in the selector would be brilliant.

Page for reference (the last selector being chosen select):
https://the-magicians-code.github.io/?action=1&subject=4&items=500&items=600

**Comment by brianvoe** [comment]
1. DeselectAll is an option I would totally be on board with.
2. Backspace deselects last option - this one is a little more tricky. Because slim select has a separate search bar, hitting backspace in that search bar would deselect the last option. I dont think I would agree to adding that. I am open to discussion but hopefully you see the issue that might cause.
