### ISSUE TITLE
The change event triggered on the original select doesn't bubble

### ISSUE THREAD

**Issue by ant7** [brianvoe/slim-select#50]
Hi @brianvoe ,

Thanks for the great work on this component.
I was wondering if it wouldn't be better to make the change event triggered on the original select bubble, just like the original change event would do? I was delegating my event listeners and noticed that the event doesn't bubble. 

Thank you
All the best

**Comment by brianvoe** [comment]
Thanks for the kind words!

I see what you are saying about this, but what i ended up landing on is to have the original select have a mutation observer on it for value and option changes but not bubble up to the slim select due to looping function call issues and to simplify functionality primarily to the slim select itself

**Comment by ant7** [comment]
Hi @brianvoe,

Thanks for answering. 
I didn't meant that the event should bubble up to the slim select, but that the change event triggered on the original select should bubble, so that event delegation could work (I prefer to use the original select for listening to changes). The change event bubbles by default (https://developer.mozilla.org/en-US/docs/Web/Events/change), so I think it should be the same in this case. Hope I explain it better this time.

Thank you
All the best

**Comment by brianvoe** [comment]
Ok i see where your coming from. I have a couple of things im making changes to right now, so ill look into this shortly and keep you updated.

Thanks.

**Comment by ant7** [comment]
Thank you, @brianvoe!

**Comment by brianvoe** [comment]
So after looking at this further i added an event listener on the original select and i am getting the change called. So if your use case of listening for a change event and bubbling, maybe you need to help me understand the next event your bubbling to.

**Comment by Shoplifter** [comment]
@brianvoe I think @ant7 is talking abput event delegation here. So the change event is actually not added (and caught) on the original select, but on a parent container. Useful, because instead of adding possibly many events on each element in the container only one venet has to be added. Also if contents are updated (e.g. via ajax) - your old container event is still working. 

Of course this works only, if events are bubbling, as the built in change event is, but not the custom event set on slim select I think.

I dont know if that interferes with other things and haven't tried, but maybe instead
`this.element.dispatchEvent(new CustomEvent('change'))`
a simple change to `this.element.dispatchEvent(new CustomEvent('change', {bubbles:true}))` 
is all that's needed?

**Comment by brianvoe** [comment]
If thats the simple change ill add it

**Comment by ant7** [comment]
Hi @brianvoe,

@Shoplifter explained it very well. This is also what I've also done for a project using SlimSelect and it works really well (didn't had the time to create PR though).

Thank you
All the best

**Comment by brianvoe** [comment]
you added the {bubbles: true} and it worked?

**Comment by brianvoe** [comment]
Ok i added it to the current develop branch im working in right now

**Comment by ant7** [comment]
Yes, it works as it's supposed to.

Thank you

**Comment by brianvoe** [comment]
ok then it will be in the next release
