### ISSUE TITLE
Search is undefined when using SS in shadow dom on firefox.

### ISSUE THREAD

**Issue by ClintCWC** [brianvoe/slim-select#523]
I'm using sim select in angular with the parent component set to encapsulation: ViewEncapsulation.ShadowDom,

this puts the parent and child components in a shadow dom (open).

I've set 
contentLocation: this.element.nativeElement as HTMLElement

this renders the list and search fine.
when using Firefox i type in the search I get a console error 'TypeError: search is undefined'

I've narrowed this down to line 749 slimselect.js the 'e.target.value' is undefined in Firefox (works ok in Chrome)

**Comment by brianvoe** [comment]
Thats not really something in my control. I cant even see what your saying. You ignored and deleted everything to submit a valid issue for me to look at. Ill post it again for you below.

**Describe the bug**
A clear and concise description of what the bug is.

**Recreate it in Codepen**
If I cant see the issue I will not look at the issue.
https://codepen.io/brianvoe/pen/MWXqXXV

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
