### ISSUE TITLE
The change event triggered on the original select doesn't bubble

### ISSUE THREAD

**Issue by pepa-linha** [brianvoe/slim-select#524]
There was already an[ issue for bubbles](https://github.com/brianvoe/slim-select/issues/50#issuecomment-425987573) created here

but in the current version the event is not with bubbles again:

https://github.com/brianvoe/slim-select/blob/master/src/slim-select/select.ts#L300

I supposed it should be
```js
this.select.dispatchEvent(new Event('change'), { bubbles: true })
```

**Comment by frenkel** [comment]
I'm affected by this as well and have created #547 based on your suggestion. It does indeed fix it for me.

**Comment by brianvoe** [comment]
I dont mind adding the pr I just need a test added for it.

**Comment by frenkel** [comment]
@brianvoe I'm trying to write tests for this and while doing so I found out that my original PR contained an error. Instead of this:

```
    this.select.dispatchEvent(new Event('change'), { bubbles: true })
```

it should have been:

```
    this.select.dispatchEvent(new Event('change', { bubbles: true }))
```

Sorry about that, I messed up in the Github web ui I guess.

Also, I don't think this fixes the case where a users selects an item. Can you help me find where the original change event is created for when a user selects an item? I'll then create a PR with tests for it.

**Comment by brianvoe** [comment]
no worries. I made the fix for you
