### ISSUE TITLE
Cannot set placeholder text for optgroup via setData 

### ISSUE THREAD

**Issue by josiahayres-ibm** [brianvoe/slim-select#77]
Hey I'm really loving this library. 

I want to dynamically set the options available, and they need to be grouped. The documentation for setData > Data Types doesn't clearly explain how to add groups, and values. 

I have figured out how to add options and group them when using setData, but I can't get the placeholder label to update when this method is called. 
 
I have created a <a href="http://jsfiddle.net/jayres/g9evjc86">JSFiddle</a> to demonstrate.

Is this simply an issue with the documentation and the data object that is being passed to the setData method? 

Cheers!

**Comment by brianvoe** [comment]
Thanks for letting me know about this. ill fix this first thing in the morning.

**Comment by brianvoe** [comment]
This is fixed. set data with placeholder will update the placeholder value. I also updated the docs and added a new section under options hopefully making it more understandable your options for single options as well as groups. v1.18.4

**Comment by josiahayres-ibm** [comment]
Lovely, thanks for getting onto it so quickly Brian :).
Can confirm issue is resolved with v1.18.4, however, inputs that don't specify placeholder text on init have no placeholder (used to have "Select Value") as default text. 
Not sure if this behaviour is intended or not? I don't have a problem with manually setting the placeholder label per option.

**Comment by brianvoe** [comment]
Im not sure i fully follow your issue. It might be that your mixing input with option?

for search placeholder text use searchPlaceholder: 'Search for the good stuff!'

**Comment by josiahayres-ibm** [comment]
I have created two demos, demonstrating the issue. Each demo has the exact same HTML and JS to initialise the selects, the only difference is the slim select version. 

[First demo (v1.18.3](http://jsfiddle.net/jayres/yd671x5s/)
v1.18.3 works as expected, when setting placeholder. 

[Second Demo (v1.18.4)](http://jsfiddle.net/jayres/awpf7xc0/)
v1.18.4 does not set any placeholder (default placeholder, OR when set at initialisation) IF the select div has `<option data-placeholder="true"></option> ` set. This is the case for both single and multiple select options. 


Hope this is a bit more clear!

**Comment by brianvoe** [comment]
Ok i see what your saying. So to give you some info on the last update i did. Basically what i added was if you set <option data-placehlder="true"></option> it will look at the html or data and if it has a data-placeholder then it will use the text in there. Thats what makes `{placeholder: true, text: 'placholder text here'}` So because options map to the data option the same meaning:
`<option data-placehlder="true"></option>`
equals
`{placeholder: true, text: 'placholder text here'}`

Ill update the docs and make a minor code change to not break backward compatibility. But an easy fix for you right now that will also work in the future is just add text inside your <option data-placeholder="true">Placeholder text here</option> that that will override the placeholder text in the configuration.

Thanks for pointing this out.

**Comment by josiahayres-ibm** [comment]
That makes sense, nice explanation! 
I've updated my implementation and it all seems to be good, really appreciate your fast response 👍🏻 Thanks!

**Comment by brianvoe** [comment]
No problem. Hope you enjoy it. Give it a star if you do. It really helps.
