### ISSUE TITLE
Feature Request:  "starts with" search behaviour

### ISSUE THREAD

**Issue by maciej-laskowski** [brianvoe/slim-select#80]
Hi, 

First of all thank you for taking the time to develop slim-select, I really like the minimalistic approach, it almost perfectly fits my use case. I was wondering if you ever considered adding an option to change default search behavior to `starts with`? Right now when users start searching and presses `a` all results containing letter `a` are be shown, with `starts with` only  results which start with `a` would be displayed.

**Comment by brianvoe** [comment]
Thanks for the kind words

So i havent tested this but what you could do is on beforeOpen you could run `select.search('a')` which might accomplish the same thing your looking for.

Let me know your thoughts, cause although i could add a starts with I try not to bloat it too much with fringe items. But im also open to things that would improve slim select in general.

**Comment by maciej-laskowski** [comment]
Sadly running `select.search('a')` triggers default search behavior and all elements containing `a` are displayed.

I like your bloat-free approach and I do wonder myself if this option should be added. I think most searches uses `starts with` as default behavior and this was what I personally expected. Maybe instead of adding an boolean option it would be better to allow usage of a custom filter function? Example:

```
new SlimSelect({
  select: '#select',
  searchFilter: (query, option) => {
    return value.startsWith(option.value)
  }
})
```
This shouldn't conflict with `searchHighlight`.

**Comment by Shoplifter** [comment]
@maciej-laskowski see my [gist](https://gist.github.com/Shoplifter/edb79896165089513895c5b1f5e2bd8f) here and issue #67 
I try to update the gist for the current version asap, its not far behind though (v.1.18.2) so give it a try if you like

**Comment by maciej-laskowski** [comment]
@Shoplifter thank you for such a quick response, looks like you had the same idea 2 weeks before me :)

I run your script with:
```
new SlimSelect({
    select: '#select',
    searchFilter: (obj, search ) => {
        return obj.text.toLowerCase().indexOf(search.toLowerCase()) === 0
    }
})
```
and it seems to be working perfectly!

**Comment by brianvoe** [comment]
👍

**Comment by maciej-laskowski** [comment]
@brianvoe What do you think about merging this feature to the official release?

**Comment by brianvoe** [comment]
So you can do this right now using the ajax parameter. The name might be misleading but all that function call back does is pass in your search and you trigger the callback of the data you want to display as the results.

**Comment by brianvoe** [comment]
@Shoplifter If you want to submit a pr change for thing implementation. Ill take a look at it and see if i can get in if you guys find it valuable enough.

**Comment by Shoplifter** [comment]
@brianvoe Unfortunately i am not capable of doing this. (no experience in typescript, vue or webpack)
I can explain what I did with the js file thoiug, if that helps.
I changed follwoing lines: (see gist)
introduce option: [574](https://gist.github.com/Shoplifter/edb79896165089513895c5b1f5e2bd8f#file-slimselect-js-L574)
set default: [993](https://gist.github.com/Shoplifter/edb79896165089513895c5b1f5e2bd8f#file-slimselect-js-L993)
use it: [458](https://gist.github.com/Shoplifter/edb79896165089513895c5b1f5e2bd8f#file-slimselect-js-L458), [467](https://gist.github.com/Shoplifter/edb79896165089513895c5b1f5e2bd8f#file-slimselect-js-L467), [481](https://gist.github.com/Shoplifter/edb79896165089513895c5b1f5e2bd8f#file-slimselect-js-L481)
@maciej-laskowski Are you familiar with the required tools to make a PR?
Otherwise I can just try to make changes in the *.ts files that seem logical to me, but that would be rather blindfolded.

**Comment by maciej-laskowski** [comment]
@Shoplifter Not really but I always wanted to so I might give it a try soon if @brianvoe doesn't find the time.

**Comment by brianvoe** [comment]
Clone it
npm install
npm run dev
localhost:8080

You can do it guys! I believe in you!

**Comment by MartinPeverelli** [comment]
@brianvoe @Shoplifter @maciej-laskowski I created the PR with the implementation discussed here: https://github.com/brianvoe/slim-select/pull/91

**Comment by brianvoe** [comment]
This will be tackled with a release today
