### ISSUE TITLE
Rename option method

### ISSUE THREAD

**Issue by professorkolik** [brianvoe/slim-select#87]
Hi @brianvoe! Thank you again for lightweight custom select solution.

Would be nice to have an ability to rename option in select, with additional option about trigger changed flag.
Would it be complex to implement?

**Comment by brianvoe** [comment]
@professorkolik YOUR WELCOME! Glad you like it

There is a mutation observer on the original select. I havent tested it yet but if you change a value on the original select it should trigger the observer and update slim select.

The second and possibly better solution is to use setData the change the data set to values you would like to use.

**Comment by professorkolik** [comment]
@brianvoe thank you for response.

Mutation observer didn't trigger when we change select option, so it won't help
Any chance to change single data item in data collection and update everything?

**Comment by brianvoe** [comment]
I dont have functionality to update a single data set. If you find yourself needing to update a single option, i would suggest if you need to make dynamic changes to your select dropdown use a javascript data set to create and update slim select. 

I use Vue for my development and most of the time my data is in an array and i loop and render out the html of the select options. and due to the reactivity system when my data changes my select html changes as well and slim select updates accordingly.

```
<select id="states">
            <option v-for="value in states" :key="value.abv" :value="value.abv" :selected="value.selected">{{value.state}}</option>
          </select>
```

That being said I would be up for accepting a pr if you wanted to add in a single update. But i think your solution is just as easily solvable by using a different method of programming.

**Comment by professorkolik** [comment]
@brianvoe You are absolutely right, I've updated manually select and slimSelect HTML with data collection accordingly in my code. I thought that it will be cleaner if it will be possible from SlimSelect itself.

Thank you for your time, I'll work on PR once have some more time!
